//==============================================================================
/** @file OpenPET.c                          
    @brief This file provides the functionality for the OpenPET main screen

### HARDWARE/FIRMWARE ENVIRONMENT
      OS    |    HW type     |    HW ver.   |          FW ver.  
	--------|----------------|--------------|-------------------------  
      Win   |    Host PC     |     N/A      |           N/A
	  
### FILE REFERENCES
    - <ansi_c.h> - NI library packaging together several common C libraries
	- <userint.h> - the NI user interface library 
	- "toolbox.h" - NI library providing support functions
	- "UI_Common.h" - UI utility structures and functions
	- "OpenPET.h" - header file linking this .c file to "OpenPET.uir"
	- "GUI_TestMode1.h" - test mode 1 analysis  
	- "GUI_TestMode2.h" - test mode 2 analysis 
	- "GUI_TestMode_MB.h" - test mode MB navigation
	- "GUI_TestMode_DUC.h" - test mode DUC navigation  
	- "GUI_TestMode_DB.h" - test mode DB navigation  
	- "GUI_EnergyMode.h" - energy mode analysis
	- "GUI_EnergyMode_MB.h" - energy mode MB navigation  
	- "GUI_EnergyMode_DUC.h" - energy mode DUC navigation  
	- "GUI_EnergyMode_DB.h" - energy mode DB navigation  
	- "GUI_FloodMapMode.h" - flood map mode analysis     
	- "GUI_FloodMapMode_MB.h" - flood map mode MB navigation    
	- "GUI_FloodMapMode_DUC.h" - flood map mode DUC navigation    
	- "GUI_TimeMode.h" - time mode analysis   
	- "GUI_TimeMode_MB.h" - time mode MB navigation 
	- "GUI_TimeMode_DUC.h" - time mode DUC navigation 
	- "GUI_TimeMode_DB.h" - time mode DB navigation 
	- "GUI_OscilloscopeMode.h" - oscilloscope mode analysis
	- "GUI_OscilloscopeMode_MB.h" - oscilloscope mode MB navigation  
	- "GUI_OscilloscopeMode_DUC.h" - oscilloscope mode DUC navigation 
	- "GUI_OscilloscopeMode_DB.h" - oscilloscope mode DB navigation 
	- "GUI_UserDefinedMode.h" - user mode analysis      
	- "GUI_UserDefinedMode_MB.h" - user mode MB navigation  
	- "GUI_UserDefinedMode_DUC.h" - user mode DUC navigation    
	- "GUI_UserDefinedMode_DB.h" - user mode DB navigation  
	
### EXTERNAL VARIABLES
    none    
	
### EXTERNAL REFERENCES
    none     
	
### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Other errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
### ASSUMPTIONS, CONSTRAINTS, RESTRICTIONS
	Assumptions for each variable and function are listed individually.	
	
### NOTES
	This panel will be the first one loaded and all other panels are called starting from this one.
	
###	ALGORITHM
	All panels are loaded into memory initially to provide faster navigation once the program has loaded. 
	Different pathways are reachable from this screen and available by user selection.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
//==============================================================================

// Doxygen documentation for Opening Page

/** @mainpage

@section intro Introduction
This page documents the code used for the OpenPET project sponsored by the Moses Laboratory at the
Lawrence Berkeley National Laboratory.

@section starting Getting Started
The complete documentation for each file and each function is given under the files tab. 

*/

//==============================================================================
// Include files

#include <ansi_c.h>
#include <userint.h>
#include "OpenPET.h"
#include "toolbox.h"

#include "UI_Common.h"
#include "System_Common.h"

#include "GUI_TestMode1.h" 
#include "GUI_TestMode2.h"
#include "GUI_TestMode_MB.h" 
#include "GUI_TestMode_DUC.h"  
#include "GUI_TestMode_DB.h"  
#include "GUI_EnergyMode.h"
#include "GUI_EnergyMode_MB.h" 
#include "GUI_EnergyMode_DUC.h" 
#include "GUI_EnergyMode_DB.h" 
#include "GUI_FloodMapMode.h"    
#include "GUI_FloodMapMode_MB.h"    
#include "GUI_FloodMapMode_DUC.h"    
#include "GUI_TimeMode.h"    
#include "GUI_TimeMode_MB.h" 
#include "GUI_TimeMode_DUC.h"
#include "GUI_TimeMode_DB.h"
#include "GUI_OscilloscopeMode.h"    
#include "GUI_OscilloscopeMode_MB.h" 
#include "GUI_OscilloscopeMode_DUC.h"
#include "GUI_OscilloscopeMode_DB.h"
#include "GUI_UserDefinedMode.h"    
#include "GUI_UserDefinedMode_MB.h"
#include "GUI_UserDefinedMode_DUC.h"  
#include "GUI_UserDefinedMode_DB.h"  
#include "GUI_SysConfig.h"
#include "GUI_Calibration.h"    

//==============================================================================
// Constants

//==============================================================================
// Types

//==============================================================================
// Static global variables

//==============================================================================
// Static functions

//==============================================================================
// Global variables
int panelHandle;					/**< main screen panel handle */
int panelHandle_testmode_mb; 		/**< test mode MB panel handle */
int panelHandle_testmode_duc; 		/**< test mode DUC panel handle */
int panelHandle_testmode_db;		/**< test mode DB panel handle */
int panelHandle_testmode1; 			/**< test mode 1 analysis screen panel handle */
int panelHandle_testmode2; 			/**< test mode 2 analysis screen panel handle */
int panelHandle_emode_mb;  			/**< energy mode MB panel handle */
int panelHandle_emode_duc; 	 		/**< energy mode DUC panel handle */
int panelHandle_emode_db;			/**< energy mode DB panel handle */
int panelHandle_emode; 				/**< energy mode analysis screen panel handle */
int panelHandle_fmmode_mb;  		/**< flood map mode MB panel handle */
int panelHandle_fmmode_duc; 	 	/**< flood map mode DUC panel handle */
int panelHandle_fmmode; 			/**< flood map mode analysis screen panel handle */
int panelHandle_timemode_mb;  		/**< time mode MB panel handle */
int panelHandle_timemode_duc; 		/**< time mode DUC panel handle */
int panelHandle_timemode_db;		/**< time mode DB panel handle */
int panelHandle_timemode; 			/**< time mode analysis screen panel handle */
int panelHandle_omode_mb;  			/**< oscilloscope mode MB panel handle */
int panelHandle_omode_duc; 	 		/**< oscilloscope mode DUC panel handle */
int panelHandle_omode_db;			/**< oscilloscope mode DB panel handle */
int panelHandle_omode; 				/**< oscilloscope mode analysis screen panel handle */
int panelHandle_usermode_mb;  		/**< user mode MB panel handle */
int panelHandle_usermode_duc; 		/**< user mode DUC panel handle */
int panelHandle_usermode_db;		/**< user mode DB panel handle */
int panelHandle_usermode; 			/**< user mode analysis screen panel handle */
int panelHandle_sysconfig;
int panelHandle_calibration;

int system_size=0;  // 1 is large, 2 is medium, 3 is small, -1 is error;

extern Stack panel_stack;
//extern PanelAppearance appearance; 
extern OpenPETTree current_location;
extern OpenPETTree sys_config;
extern OpenPETSystemNode *sys_config1; 

//==============================================================================
// Global functions

/** @brief This is the main entry-point function.
	@param argc the argument count
	@param *argv[] the argument vector
	@return integer indicating reason for exit. 0 indicates success

### EXTERNAL VARIABLES
	- extern Stack @ref panel_stack - "UI_Common.c"
	- extern OpenPETTree @ref current_location - "UI_Common.c"
	- extern OpenPETSysConfig @ref sys_config - "UI_Common.c"  

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	After any necessary initialization, each panel is loaded into memory, the first panel is displayed, and the user interface is initiated.
	If there is an error, all panels are cleaned up and discarded using the tools from toolbox.h.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int main (int argc, char *argv[])
{
    int error = 0;
    
    /* initialize and load resources */
	StackInit(&panel_stack);
	OpenPETTreeInit(&current_location);
	sys_config.MB=1;
	sys_config.DUC=7;
	sys_config.DB=7;
	
	OpenPETSystemCreateExample(sys_config1, 1);
	system_size = SystemSize(sys_config1);
	

    nullChk (InitCVIRTE (0, argv, 0));
    errChk (panelHandle = LoadPanel (0, "OpenPET.uir", PANEL));
	errChk (panelHandle_testmode1 = LoadPanel (0, "GUI_TestMode1.uir", TESTMODE1));   
	errChk (panelHandle_testmode2 = LoadPanel (0, "GUI_TestMode2.uir", TESTMODE2)); 
	errChk (panelHandle_testmode_mb = LoadPanel (0, "GUI_TestMode_MB.uir", TESTMODEMB));
	errChk (panelHandle_testmode_duc = LoadPanel (0, "GUI_TestMode_DUC.uir", TESTMODEDU)); 
	errChk (panelHandle_testmode_db = LoadPanel (0, "GUI_TestMode_DB.uir", TESTMODEDB)); 
	errChk (panelHandle_emode = LoadPanel (0, "GUI_EnergyMode.uir", EMODE)); 
	errChk (panelHandle_emode_mb = LoadPanel (0, "GUI_EnergyMode_MB.uir", EMODEMB));  
	errChk (panelHandle_emode_duc = LoadPanel (0, "GUI_EnergyMode_DUC.uir", EMODEDU));  
	errChk (panelHandle_emode_db = LoadPanel (0, "GUI_EnergyMode_DB.uir", EMODEDB));  
	errChk (panelHandle_fmmode = LoadPanel (0, "GUI_FloodMapMode.uir", FMMODE)); 
	errChk (panelHandle_fmmode_mb = LoadPanel (0, "GUI_FloodMapMode_MB.uir", FMMODEMB)); 
	errChk (panelHandle_fmmode_duc = LoadPanel (0, "GUI_FloodMapMode_DUC.uir", FMMODEDU)); 
	errChk (panelHandle_timemode = LoadPanel (0, "GUI_TimeMode.uir", TIMEMODE)); 
	errChk (panelHandle_timemode_mb = LoadPanel (0, "GUI_TimeMode_MB.uir", TIMEMODEMB)); 	
	errChk (panelHandle_timemode_duc = LoadPanel (0, "GUI_TimeMode_DUC.uir", TIMEMODEDU));
	errChk (panelHandle_timemode_db = LoadPanel (0, "GUI_TimeMode_DB.uir", TIMEMODEDB));
	errChk (panelHandle_omode = LoadPanel (0, "GUI_OscilloscopeMode.uir", OMODE)); 
	errChk (panelHandle_omode_mb = LoadPanel (0, "GUI_OscilloscopeMode_MB.uir", OMODEMB)); 
	errChk (panelHandle_omode_duc = LoadPanel (0, "GUI_OscilloscopeMode_DUC.uir", OMODEDU)); 
	errChk (panelHandle_omode_db = LoadPanel (0, "GUI_OscilloscopeMode_DB.uir", OMODEDB)); 
	errChk (panelHandle_usermode = LoadPanel (0, "GUI_UserDefinedMode.uir", USERMODE)); 
	errChk (panelHandle_usermode_mb = LoadPanel (0, "GUI_UserDefinedMode_MB.uir", USERMODEMB)); 
	errChk (panelHandle_usermode_duc = LoadPanel (0, "GUI_UserDefinedMode_DUC.uir", USERMODEDU)); 
	errChk (panelHandle_usermode_db = LoadPanel (0, "GUI_UserDefinedMode_DB.uir", USERMODEDB)); 
	errChk (panelHandle_sysconfig = LoadPanel (0, "GUI_SysConfig.uir", SYSCONFIG));
	errChk (panelHandle_calibration = LoadPanel (0, "GUI_Calibration.uir", CALIBRATE));
    
    /* display the panel and run the user interface */
    errChk (DisplayPanel (panelHandle));
    errChk (RunUserInterface ());

Error:
    /* clean up */
    DiscardPanel (panelHandle);
	DiscardPanel (panelHandle_testmode1); 
	DiscardPanel (panelHandle_testmode2);
	DiscardPanel (panelHandle_testmode_mb); 
	DiscardPanel (panelHandle_testmode_duc);
	DiscardPanel (panelHandle_testmode_db);
	DiscardPanel (panelHandle_emode); 
	DiscardPanel (panelHandle_emode_mb);
	DiscardPanel (panelHandle_emode_duc); 
	DiscardPanel (panelHandle_emode_db); 
	DiscardPanel (panelHandle_fmmode);   
	DiscardPanel (panelHandle_fmmode_mb); 
	DiscardPanel (panelHandle_fmmode_duc); 
	DiscardPanel (panelHandle_timemode);   
	DiscardPanel (panelHandle_timemode_mb); 
	DiscardPanel (panelHandle_timemode_duc);
	DiscardPanel (panelHandle_timemode_db);
	DiscardPanel (panelHandle_omode);   
	DiscardPanel (panelHandle_omode_mb);
	DiscardPanel (panelHandle_omode_duc);
	DiscardPanel (panelHandle_omode_db);
	DiscardPanel (panelHandle_usermode);   
	DiscardPanel (panelHandle_usermode_mb); 
	DiscardPanel (panelHandle_usermode_duc); 
	DiscardPanel (panelHandle_usermode_db); 
	DiscardPanel (panelHandle_sysconfig);
	DiscardPanel (panelHandle_calibration);
    return 0;
}

																														
//==============================================================================
// UI callback function prototypes

/** @brief This is the panel callback function to handle panel events
	@param panel the panel handle of the panel on which the button is used
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### EXTERNAL VARIABLES
	- extern Stack @ref panel_stack - "UI_Common.c"
	- extern OpenPETTree @ref current_location - "UI_Common.c"
	- extern OpenPETSysConfig @ref sys_config - "UI_Common.c"  

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	After any necessary initialization, each panel is loaded into memory, the first panel is displayed, and the user interface is initiated.
	If there is an error, all panels are cleaned up and discarded using the tools from toolbox.h.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK panelCB (int panel, int event, void *callbackData,
        int eventData1, int eventData2)
{
    if (event == EVENT_CLOSE)
        QuitUserInterface (0);
    return 0;
}

/** @brief This is the function callback to implement the Collect New Data button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	This button is used for the user to select the pathway to collect new data. The appropriate buttons are
	displayed and those that are not appropriate are hidden.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK CollectNewData (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			SetCtrlAttribute (PANEL, PANEL_SETUP, ATTR_VISIBLE, 1);
			SetCtrlAttribute (PANEL, PANEL_CALIBRATE, ATTR_VISIBLE, 1);
			SetCtrlAttribute (PANEL, PANEL_RUN, ATTR_VISIBLE, 1);
			
			SetCtrlAttribute (PANEL, PANEL_FILETEXT, ATTR_VISIBLE, 0); 
			SetCtrlAttribute (PANEL, PANEL_LOAD, ATTR_VISIBLE, 0); 
			SetCtrlAttribute (PANEL, PANEL_GO, ATTR_VISIBLE, 0);  
			
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON, ATTR_VISIBLE, 0); 
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_2, ATTR_VISIBLE, 0);  
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_3, ATTR_VISIBLE, 0);  
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_4, ATTR_VISIBLE, 0);
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_5, ATTR_VISIBLE, 0);
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_6, ATTR_VISIBLE, 0);
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_7, ATTR_VISIBLE, 0);
			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the Analyze Existing Data button 
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	This button is used for the user to select the pathway to analyze existing data. The appropriate buttons are
	displayed and those that are not appropriate are hidden.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK AnalyzeExistingData (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			SetCtrlAttribute (PANEL, PANEL_FILETEXT, ATTR_VISIBLE, 1); 
			SetCtrlAttribute (PANEL, PANEL_LOAD, ATTR_VISIBLE, 1);  
			SetCtrlAttribute (PANEL, PANEL_GO, ATTR_VISIBLE, 1);  
			
			SetCtrlAttribute (PANEL, PANEL_SETUP, ATTR_VISIBLE, 0);
			SetCtrlAttribute (PANEL, PANEL_CALIBRATE, ATTR_VISIBLE, 0);
			SetCtrlAttribute (PANEL, PANEL_RUN, ATTR_VISIBLE, 0);
			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the Setup button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The main screen is hidden and the opening setup panel is displayed.

###	NOTES
	This button is used for the user to setup an OpenPET hardware configure for the first time. It is not expected that 
	a user will desire to set up a new configuration each time this GUI is launched. If the Setup button is not clicked,
	the last system configuration file will be used.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK Setup (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			DisplayPanel (panelHandle_sysconfig);
			StackPush(&panel_stack, panelHandle);
			HidePanel (panelHandle);
			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the Calibrate button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The main panel is hidden and the opening panel for system calibration is displayed

###	NOTES
	Calibrating a system requires runnning single event data (including oscilloscope mode). It is not expected
	that a user will run system calibration every time they wish to use the OpenPET system, but it is expected 
	that calibration will be performed on a weekly to monthly basis. Like system setup, if the calibration 
	button is not clicked, the system will default to the most recent calibration file in use.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK Calibrate (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			DisplayPanel (panelHandle_calibration);
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the Run button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The main panel is hidden and the opening panel for running the system in coincidence mode is displayed

###	NOTES
	If the user clicks on this button, system configuration and system calibration files must be present.
	
###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK Run (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:

			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the load file button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	Allow the user to select a file for analysis through the LabWindows file select popup.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK LoadDataFile (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			// FileSelectPopup ("c:\\Documents and Settings\\OpenPET\\My Documents\\GitHub\\HostPC\\GUI\\Project", "*.*", "", "", VAL_LOAD_BUTTON, 0, 0, 1, 0, analysis_file);
			break;
	}
	return 0;
}

/** @brief This is the function callback to implement the Go button
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The data type is determined, and the appropriate first panel for navigation is launched.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK Go (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	//Header header;
	switch (event)
	{
		case EVENT_COMMIT: 
			// view status word to determine analysis type
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON, ATTR_VISIBLE, 1); 
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_2, ATTR_VISIBLE, 1);  
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_3, ATTR_VISIBLE, 1);  
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_4, ATTR_VISIBLE, 1);
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_5, ATTR_VISIBLE, 1);
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_6, ATTR_VISIBLE, 1); 
			SetCtrlAttribute (PANEL, PANEL_COMMANDBUTTON_7, ATTR_VISIBLE, 1);  
			
			//header = CreateHeader("test.txt", "User comment.", 30.0, "single");
			
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the energy mode pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayEnergyMode (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Energy Mode");
			if(system_size == 1)
				DisplayPanel (panelHandle_emode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_emode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_emode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the test mode 1 pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayTestMode1 (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Test Mode 1");
			if(system_size == 1)
				DisplayPanel (panelHandle_testmode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_testmode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_testmode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the test mode 2 pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayTestMode2 (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Test Mode 2");
			if(system_size == 1)
				DisplayPanel (panelHandle_testmode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_testmode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_testmode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the flood map mode pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayFloodMapMode (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Flood Map Mode"); 
			if(system_size == 1)
				DisplayPanel (panelHandle_fmmode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_fmmode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_fmmode);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the time mode pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayTimeMode (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Time Mode"); 
			if(system_size == 1)
				DisplayPanel (panelHandle_timemode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_timemode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_timemode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the oscilloscope mode pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayOscilloscopeMode (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"Oscilloscope Mode"); 
			if(system_size == 1)
				DisplayPanel (panelHandle_omode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_omode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_omode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}

/** @brief This function is called to display the first panel along the user mode pathway
	@param panel the panel handle of the panel on which the button is used
	@param control the control on which the event is generated 
	@param event the type of event generated (i.e. left-click causes EVENT_COMMIT)
	@param *callbackData stores the data returned to the UI handled internally by LabWindows
	@param eventData1 stores ancillary information such as the mouse x-position within the panel
	@param eventData2 stores ancillary information such as the mouse y-position within the panel
	@return 1 or 0 specifies whether or not the event should be swallowed. 0 is default-no and 1 is yes-swallow.

### ABNORMAL TERMINATION CONDITIONS, ERROR AND WARNING MESSAGES
	Errors may be generated by CVI/LabWindows. The LabWindows documentation is available online 
	at <a href="linkURL"> http://zone.ni.com/reference/en-XX/help/370051V-01/ </a>.
	
###	ALGORITHM
	The global mode type is saved, the stack is updated, and the proper panel is displayed.

###	DEVELOPMENT HISTORY
       Date    |  Author         |  Email Address     | Ver. |Description Of Change  
	   --------|-----------------|--------------------|------|---------------------
	 08/09/2013| George Netscher | gmnetscher@lbl.gov | 1.0  |conclusion of summer work
	 
### Copyright (c) 2013 by LBNL. All Rights Reserved.
*/
int CVICALLBACK DisplayUserMode (int panel, int control, int event,
		void *callbackData, int eventData1, int eventData2)
{
	switch (event)
	{
		case EVENT_COMMIT:
			strcpy(current_location.mode,"User Mode"); 
			if(system_size == 1)
				DisplayPanel (panelHandle_usermode_mb);
			else if(system_size == 2)
				DisplayPanel (panelHandle_usermode_duc);
			else if(system_size == 3)
				DisplayPanel (panelHandle_usermode_db);
			else
			{
				fprintf(stderr, "Error: Could not determine system size in main screen");
				exit(1);
			}
			StackPush(&panel_stack, panel);
			HidePanel (panel);
			break;
	}
	return 0;
}
